# Generated by Django 5.1.3 on 2024-11-28 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('original_code_block', models.CharField(max_length=1028)),
                ('modified_code_block', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.IntegerField(default=0)),
                ('bin_index', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProblemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('best_key_strokes', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('best_speed', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
