# Generated by Django 5.1.3 on 2024-12-02 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemStatistics',
            new_name='Problem_Statistics',
        ),
        migrations.RenameModel(
            old_name='UserProblemStatistics',
            new_name='User_Problem_Statistics',
        ),
    ]
