# Generated by Django 5.1.3 on 2024-12-02 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 3, 55, 28, 346147, tzinfo=datetime.timezone.utc)),
        ),
    ]
